# /// script
# requires-python = ">=3.10"
# dependencies = ["jsonschema>=4.21", "pyyaml>=6"]
# ///
"""Cross-harness contract tests for the skills themselves (issue #31).

Usage:
  uv run tests/integrations/test_cross_harness.py                     # replay every recording (offline)
  uv run tests/integrations/test_cross_harness.py --harness codex     # replay one harness
  uv run tests/integrations/test_cross_harness.py --live claude-code  # run all three legs live
  uv run tests/integrations/test_cross_harness.py --live codex --leg rubric --record

One fixture, built from the committed Demo Corpus (failed outputs, domain
rules, human labels), run through each harness (`claude -p`, `codex exec`) on
three legs — analyze, rubric, validate. What is asserted is semantic, never
prose: schema validity, provenance grounded in the fixture inventory, veto
semantics preserved against the human labels, and the replay detections the
audit must surface. The same check functions run over a live run and over a
recording; only where the artifacts came from differs.

Offline is the default: `recordings/<harness>/<leg>/` holds artifacts a real
harness produced (`run.json` records which CLI, model and date), replayed onto
a freshly built fixture. Live runs need a logged-in CLI and cost real calls, so
they run on dispatch (.github/workflows/cross-harness.yml), never on a PR —
consistent with ADR-0002: nothing here asserts that an LLM reproduces a defect,
only that whatever it writes satisfies the contract.
"""
import argparse
import json
import pathlib
import re
import shutil
import subprocess
import sys
import tempfile
import time
from datetime import date

import yaml
from jsonschema import Draft202012Validator

HERE = pathlib.Path(__file__).resolve().parent
ROOT = HERE.parents[1]
SCRIPTS = ROOT / "scripts"
SCHEMAS = ROOT / "schemas"
INPUTS = ROOT / "demo" / "inputs"
GOLDEN = ROOT / "demo" / "golden-pack"
RECORDINGS = HERE / "recordings"

# Generated by audit_pack.py / export_*.py and gitignored: a copy must never
# carry them in, or a leg could "pass" on artifacts no harness produced.
GENERATED = {"coverage-matrix.yaml", "eval-audit.md", "exports", "__pycache__"}

ok = True
failures = []


def expect(cond, msg):
    global ok
    if not cond:
        ok = False
        failures.append(msg)
        print(f"  FAIL {msg}")
    return cond


def run_script(name, *args):
    p = subprocess.run(["uv", "run", str(SCRIPTS / name), *map(str, args)],
                       capture_output=True, text=True, cwd=ROOT)
    return p.returncode, p.stdout + p.stderr


# --------------------------------------------------------------- the fixture
def calibration_cases():
    return [json.loads(l) for l in (GOLDEN / "calibration.jsonl").read_text().splitlines() if l.strip()]


def failed_outputs_md():
    """The 5 known failed outputs + their human labels, rendered from the corpus.

    The agent description names them as `task-id/candidate-id`; the text and the
    label live in calibration.jsonl. Rendering keeps one canonical copy.
    """
    cases = {f"{c['task_id']}/{c['candidate']['id']}": c for c in calibration_cases()}
    refs = [r for r in re.findall(r"`([a-z0-9-]+/[a-z0-9-]+)`",
                                  (INPUTS / "agent-description.md").read_text()) if r in cases]
    L = ["# Known failed outputs, with the reviewers' labels", "",
         "The five failures named in the agent description, as captured, each with",
         "the human reviewer's verdict.", ""]
    for ref in refs:
        c = cases[ref]
        L += [f"## `{ref}`", "",
              f"Human label: **{c['expected']['final_result']}** — {c['reason']}", "",
              "Output as produced:", "", "```text", c["candidate"]["output"].strip(), "```", ""]
    return "\n".join(L)


def copy_pack(dest, drop=()):
    shutil.copytree(GOLDEN, dest,
                    ignore=lambda _d, names: [n for n in names if n in GENERATED or n in drop])


def setup_analyze(ws):
    shutil.copytree(INPUTS, ws / "inputs")
    shutil.copytree(GOLDEN / "sources", ws / "inputs" / "sources")  # the packet the rules are about
    (ws / "inputs" / "failed-outputs.md").write_text(failed_outputs_md())
    (ws / "pack").mkdir()


def setup_rubric(ws):
    # Rubric phase inputs only: the draft rubric in fixtures/ is a planted
    # defect (ADR-0002) and must not be available to copy from.
    copy_pack(ws / "pack", drop={"rubric.yaml", "judge-protocol.yaml",
                                 "human-review-guide.md", "fixtures"})


def setup_validate(ws):
    copy_pack(ws / "pack")  # incl. fixtures/scripted-verdicts.jsonl — the replay judge


# ------------------------------------------------------------- the invariants
def inventory_labels():
    """Every label a grounded provenance pointer may cite, from the fixture itself."""
    labels = {"agent description", "domain rule", "task brief", "failed output",
              "agent-description.md", "domain-rules.md", "task-briefs.md", "failed-outputs.md"}
    for c in calibration_cases():
        labels |= {c["task_id"], c["candidate"]["id"], f"{c['task_id']}/{c['candidate']['id']}"}
    labels |= {f"rule {n}" for n in
               re.findall(r"^(\d+)\.", (INPUTS / "domain-rules.md").read_text(), re.M)}
    labels |= set(re.findall(r"`([a-z0-9-]+)`", (INPUTS / "task-briefs.md").read_text()))
    labels |= {p.name for p in (GOLDEN / "sources").iterdir()}
    labels |= {p.stem for p in (GOLDEN / "sources").iterdir()}
    return {l.lower() for l in labels}


def check_analyze(pack):
    code, out = run_script("check_analysis.py", pack)
    expect(code == 0, f"check_analysis.py not green:\n{out}")

    taxonomy = yaml.safe_load((pack / "failure-taxonomy.yaml").read_text())
    modes = taxonomy["failure_modes"]
    labels = inventory_labels()
    for m in modes:
        prov = m.get("provenance") or []
        if not expect(prov, f"failure mode {m['id']}: no provenance (grounding gate)"):
            continue
        for p in prov:
            text = str(p).lower()
            expect(any(l in text for l in labels),
                   f"failure mode {m['id']}: provenance cites nothing in the inventory: {p!r}")
    expect(any(m["severity"] in ("critical", "high") for m in modes),
           "no critical/high failure mode — the packet's zero-tolerance rule went unrecognized")
    expect((pack / "eval-problem.md").read_text().strip(), "eval-problem.md empty")


def check_rubric(pack):
    code, out = run_script("check_rubric.py", pack)
    expect(code == 0, f"check_rubric.py not green:\n{out}")

    rubric = yaml.safe_load((pack / "rubric.yaml").read_text())
    kinds = {c["id"]: c["kind"] for c in rubric["criteria"]}
    expected_vetoes = {k for c in calibration_cases() for k in c["expected"]["vetoes"]}
    expect(expected_vetoes, "fixture has no human-labelled vetoes — check calibration.jsonl")
    for k in sorted(expected_vetoes):
        expect(kinds.get(k) == "veto",
               f"veto semantics lost: human labels record veto {k}; rubric has "
               f"{'kind: ' + kinds[k] if k in kinds else 'no such criterion'}")

    proto = yaml.safe_load((pack / "judge-protocol.yaml").read_text())
    expect("veto" in json.dumps(proto.get("aggregation", "")).lower(),
           "judge-protocol.yaml aggregation rule says nothing about vetoes — a veto that "
           "does not decide final_result is a weighted criterion wearing the name")


# The replay judge and the planted coverage gap are deterministic: whatever the
# harness writes, running the audit must surface these four (demo/README.md).
DETECTIONS = [
    (r"`coverage_gap`.*misattributed_quote", "coverage_gap on misattributed_quote"),
    (r"`judge_disagreement`.*fluent-conflict-gloss", "judge_disagreement on fluent-conflict-gloss"),
    (r"`order_sensitivity`.*near-tie", "order_sensitivity on the near-tie pair"),
    (r"`calibration_failure`.*citation-stuffing", "calibration_failure on citation-stuffing"),
]


def check_validate(pack):
    audit = (pack / "eval-audit.md").read_text()
    for pattern, what in DETECTIONS:
        expect(re.search(pattern, audit) is not None, f"audit missing detection: {what}")
    expect("(runner: replay)" in audit, "audit was not produced by the replay runner")

    matrix = yaml.safe_load((pack / "coverage-matrix.yaml").read_text())
    schema = json.loads((SCHEMAS / "coverage-matrix.schema.json").read_text())
    for e in Draft202012Validator(schema).iter_errors(matrix):
        expect(False, f"coverage-matrix.yaml: {'/'.join(map(str, e.absolute_path))}: {e.message}")
    gaps = {r["failure_mode"] for r in matrix["rows"] if r["status"] == "gap"}
    expect("misattributed_quote" in gaps,
           f"coverage matrix does not flag the planted gap: gaps={sorted(gaps)}")


# ------------------------------------------------------------------- the legs
PREAMBLE = f"""Non-interactive run: never ask the user anything, make reasonable choices and proceed.
Wherever a skill writes `${{CLAUDE_PLUGIN_ROOT}}`, it means {ROOT}; run bundled scripts as
`uv run {ROOT}/scripts/<name>.py`.
"""

LEGS = {
    "analyze": dict(
        setup=setup_analyze,
        outputs=["eval-problem.md", "failure-taxonomy.yaml", "evaluation-dimensions.yaml"],
        check=check_analyze,
        prompt=f"""{PREAMBLE}
Run EvalGrill's analyze phase using the analyze-eval-problem skill.

Evidence to inventory, each read in full: inputs/agent-description.md,
inputs/domain-rules.md, inputs/task-briefs.md, inputs/failed-outputs.md, and the
source packet those tasks attach, inputs/sources/.
EvalPack directory: ./pack (already created; write the phase artifacts there).

You are done when `uv run {ROOT}/scripts/check_analysis.py ./pack` prints OK.""",
    ),
    "rubric": dict(
        setup=setup_rubric,
        outputs=["rubric.yaml", "judge-protocol.yaml", "human-review-guide.md"],
        check=check_rubric,
        prompt=f"""{PREAMBLE}
Run EvalGrill's rubric phase using the design-eval-rubric skill on the existing
EvalPack at ./pack.

It already holds failure-taxonomy.yaml, evaluation-dimensions.yaml, dataset.jsonl
and calibration.jsonl (the human labels). Write rubric.yaml, judge-protocol.yaml
and human-review-guide.md into ./pack.

You are done when `uv run {ROOT}/scripts/check_rubric.py ./pack` prints OK.""",
    ),
    "validate": dict(
        setup=setup_validate,
        outputs=["eval-audit.md", "coverage-matrix.yaml"],
        check=check_validate,
        prompt=f"""{PREAMBLE}
Run EvalGrill's validate phase using the validate-eval-design skill on the
EvalPack at ./pack.

Use the replay runner (pass `--runner replay`): no live judge calls, no API keys.
Report the detections you find; do not edit the pack's canonical artifacts.

You are done when ./pack/eval-audit.md and ./pack/coverage-matrix.yaml exist.""",
    ),
}


# -------------------------------------------------------------- the harnesses
def run_claude(ws, prompt, timeout):
    cmd = ["claude", "-p", prompt, "--plugin-dir", str(ROOT),
           "--permission-mode", "bypassPermissions", "--output-format", "json"]
    return subprocess.run(cmd, cwd=ws, capture_output=True, text=True, timeout=timeout)


def run_codex(ws, prompt, timeout):
    # Codex discovers skills under <project>/.agents/skills (integrations/codex);
    # symlinks, not copies, so the canonical tree stays single-source (ADR-0003).
    skills = ws / ".agents" / "skills"
    skills.mkdir(parents=True)
    for s in sorted((ROOT / "skills").iterdir()):
        (skills / s.name).symlink_to(s)
    # Full access: the leg writes the pack and `uv run` fetches PEP 723 deps, and
    # workspace-write blocks network. Everything it can reach is the temp workspace.
    cmd = ["codex", "exec", "--sandbox", "danger-full-access", "--skip-git-repo-check",
           "-C", str(ws), prompt]
    return subprocess.run(cmd, cwd=ws, capture_output=True, text=True, timeout=timeout)


def cli_version(harness):
    cmd = {"claude-code": ["claude", "--version"], "codex": ["codex", "--version"]}[harness]
    try:
        return subprocess.run(cmd, capture_output=True, text=True).stdout.strip()
    except FileNotFoundError:
        return "not installed"


HARNESSES = {"claude-code": run_claude, "codex": run_codex}


# ------------------------------------------------------------------ the modes
def build_workspace(leg_name):
    ws = pathlib.Path(tempfile.mkdtemp(prefix=f"evalgrill-{leg_name}-"))
    LEGS[leg_name]["setup"](ws)
    return ws


def replay(harness, leg_name):
    """Assert the recorded artifacts against a freshly built fixture."""
    rec = RECORDINGS / harness / leg_name
    if not expect(rec.is_dir(), f"{harness}/{leg_name}: no recording at {rec.relative_to(ROOT)}"):
        return
    ws = build_workspace(leg_name)
    try:
        for f in LEGS[leg_name]["outputs"]:
            if not expect((rec / f).exists(), f"{harness}/{leg_name}: recording missing {f}"):
                return
            shutil.copy(rec / f, ws / "pack" / f)
        LEGS[leg_name]["check"](ws / "pack")
        meta = json.loads((rec / "run.json").read_text())
        print(f"  replayed {harness}/{leg_name} — {meta['cli_version']}, "
              f"recorded {meta['recorded_at']}")
    finally:
        shutil.rmtree(ws, ignore_errors=True)


def live(harness, leg_name, record, timeout):
    leg = LEGS[leg_name]
    before = len(failures)
    ws = build_workspace(leg_name)
    print(f"  {harness}/{leg_name}: live run in {ws}")
    started = time.time()
    try:
        p = HARNESSES[harness](ws, leg["prompt"], timeout)
        rc, tail = p.returncode, (p.stdout or "")[-2000:] + (p.stderr or "")[-2000:]
    except subprocess.TimeoutExpired:
        rc, tail = -1, f"timed out after {timeout}s"
    elapsed = round(time.time() - started, 1)
    expect(rc == 0, f"{harness}/{leg_name}: harness exited {rc}\n{tail}")
    print(f"  {harness}/{leg_name}: harness finished in {elapsed}s")

    pack = ws / "pack"
    produced = [f for f in leg["outputs"] if (pack / f).exists()]
    for f in leg["outputs"]:
        expect(f in produced, f"{harness}/{leg_name}: harness produced no {f}")
    if len(produced) == len(leg["outputs"]):
        leg["check"](pack)

    if record and produced:
        rec = RECORDINGS / harness / leg_name
        rec.mkdir(parents=True, exist_ok=True)
        for f in produced:
            shutil.copy(pack / f, rec / f)
        # Provenance for the recording. The prompt is not stored: it lives in
        # this file, and it carries an absolute repo path that differs per clone.
        (rec / "run.json").write_text(json.dumps({
            "harness": harness, "leg": leg_name, "cli_version": cli_version(harness),
            "recorded_at": date.today().isoformat(), "duration_s": elapsed, "exit_code": rc,
        }, indent=2) + "\n")
        print(f"  recorded -> {rec.relative_to(ROOT)}")
    if len(failures) == before:
        shutil.rmtree(ws, ignore_errors=True)
    else:
        print(f"  workspace kept for inspection: {ws}")


def main():
    ap = argparse.ArgumentParser(description=__doc__)
    ap.add_argument("--live", choices=sorted(HARNESSES), help="run the legs live through this harness")
    ap.add_argument("--harness", choices=sorted(HARNESSES), help="replay only this harness")
    ap.add_argument("--leg", choices=sorted(LEGS), help="one leg instead of all three")
    ap.add_argument("--record", action="store_true", help="with --live: write the recording")
    ap.add_argument("--timeout", type=int, default=1800, help="per live leg, seconds")
    args = ap.parse_args()

    legs = [args.leg] if args.leg else list(LEGS)
    if args.live:
        print(f"live: {args.live} ({cli_version(args.live)})")
        for leg in legs:
            live(args.live, leg, args.record, args.timeout)
    else:
        for harness in ([args.harness] if args.harness else sorted(HARNESSES)):
            print(f"replay: {harness}")
            for leg in legs:
                replay(harness, leg)

    print()
    if failures:
        print(f"FAILED: {len(failures)} assertion(s) above")
        sys.exit(1)
    print(f"OK: cross-harness contract green ({len(legs)} leg(s))")


main()
